* Bash configuration

This configuration is built over [[https://github.com/Bash-it/bash-it][bash-it]], a collection of community Bash commands and scripts, /a là/ [[https://github.com/robbyrussell/oh-my-zsh][oh-my-zsh]].

** =custom.bash=
:PROPERTIES:
:TANGLE: bash/custom.bash
:PADLINE: no
:MKDIRP: yes
:END:

This file keeps custom general configurations

*** Theme for =bash-it=

#+BEGIN_SRC sh
export BASH_IT_THEME='powerline'
#+END_SRC

*** Theme for =ls=

I like a lot [[http://ethanschoonover.com/solarized][solarized]] colorscheme, so I was lucky to find [[https://github.com/seebi/dircolors-solarized][this]].

#+BEGIN_SRC sh
eval `dircolors ${HOME}/.dircolors-solarized/dircolors.256dark`
#+END_SRC

*** =$PATH= configuration
**** Special folders
***** =0.Inbox=

Unprocessed items that don’t have a place yet in here. It is a temporary folder for files you're messing around with but don't need to save long-term. This may be items like software installers you’ve downloaded, files sent to you from colleagues, random text clippings and testing scripts. Files I decide I want to keep graduate from =0.sandbox= to =1.docs=. This folder must be emptied everyday. To avoid procrastination, resulting in a completely cluttered folder, you can keep a 'janitor' script, deleting its contents regularly.
#+BEGIN_SRC sh
INBOX=${HOME}/0.Inbox/
#+END_SRC

***** =1.Documents=

Is the big kahuna(*) of all directories. It's the place where all the working files for your currently in-progress tasks, projects and clients go. Each project gets its own unique directory. You may have many sub-folders in this directory, but don't go deeper than 3 subfolders. This directory changes often and frequently, so you must clean it regularly. Because of this most of the files here are kept under github/gitlab control.

(*) Kahuna is a Hawaiian word, defined in Pukui & Elbert (1986) as a "priest, sorcerer, magician, wizard, minister, expert in any profession". (See also Ancient Hawaii.) Forty types of kahuna are listed in the book Tales from the Night Rainbow.
#+BEGIN_SRC sh
DOCS=${HOME}/1.Documents/
#+END_SRC

***** =2.Archive*=

Completed projects, general reference items, and anything else which is important and you might want to look at again go here. From here you can create aliases for the default folder from your system, like 'Books' or 'Pictures'.  The files here don't change much if ever, and so you can back them up on a different (less frequent) schedule. Therefore I elected this folder to be actually a symbolic link to my Dropbox folder.
#+BEGIN_SRC sh
ARCHIVE=${HOME}/2.Archive/
#+END_SRC

***** =3.Media=

Multimedia files (games, pictures and movies)
#+BEGIN_SRC sh
ARCHIVE=${HOME}/3.Media/
#+END_SRC

***** =4.Opt=

Third-party software, not present among the official packages.
#+BEGIN_SRC sh
OPT=${HOME}/4.Opt
#+END_SRC

***** Put everything together

#+BEGIN_SRC sh
export PATH=${OPT}/bin:${HOME}/.bin:${HOME}/.local/bin:${PATH}
#+END_SRC

*** Eternal bash history

#+BEGIN_SRC sh
export HISTSIZE=
export HISTFILESIZE=
export HISTTIMEFORMAT="[%F %T] "
export HISTCONTROL=erasedups
export HISTFILE="${HOME}/.bash_eternal_history"
PROMPT_COMMAND="history -a; $PROMPT_COMMAND"
#+END_SRC

*** Tmux terminal setting

#+BEGIN_SRC sh
export TERM=xterm-256color
#+END_SRC

** =custom.aliases.bash=
:PROPERTIES:
:TANGLE: bash/custom.aliases.bash
:PADLINE: no
:MKDIRP: yes
:END:

This file stores additional aliases

*** Archive Extracter

Linux provides various tools for archiving and compressing files such as [[https://en.wikipedia.org/wiki/Zip_(file_format)][zip]], [[https://en.wikipedia.org/wiki/Bzip2][bzip]], [[https://en.wikipedia.org/wiki/Gzip][gzip]], [[https://en.wikipedia.org/wiki/Tar_(computing)][tar]], [[https://en.wikipedia.org/wiki/RAR_(file_format)][rar]], /etc/. There are more tools that are not native to Linux, but provide good archiving and compressing abilities. With such a large number of tools at hand, sometimes it becomes difficult to remember all the commands. '[[http://www.nongnu.org/atool/][atool]]' allows you to manage these different file archives with a single command.
#+BEGIN_SRC sh
alias ae='aunpack' # ae = mnemonic for Archive Extracter
#+END_SRC

*** Misc

#+BEGIN_SRC sh
alias df="df -H"
alias du="du -ch"
#+END_SRC
