#+title: ranger configuration
#+property: header-args  :mkdirp yes
#+property: header-args+ :tangle-mode (identity #o444)
#+property: header-args+ :noweb yes

[[https://ranger.github.io/][ranger]] is a console file manager with VI key bindings. It uses 4 main configuration files:
- =commands.py= contains various functions' implementation, written in Python, used to modify ranger's behavior,
- =rc.conf= is used for setting various options and binding the keys to functions,
- =rifle.conf= decides which program to use for opening which file,
- =scope.sh= is a shell script used to generate the previews for various file types.

It's quite common to use =ranger --copy-config=all= to copy the default config files to =~/.config/ranger= and modify them there. Be aware that for =rc.conf= and =commands.py=, ranger reads *BOTH* the global and the user's config (in that order). It allows the user to maintain only a small config which sets only the things not set in the default one. =For scope.sh= and =rifle.conf=, ranger reads either the users or the global config.

The best practice is to only add the options/keybindings you actually want to change to your =rc.conf=, rather than to have a complete copy of the default =rc.conf=. This eliminates the need to update your config manually and gives you the benefits from new options/keybindings of future ranger versions. If you want to keep the full =rc.conf= though, you may want to set the environment variable =RANGER_LOAD_DEFAULT_RC= to =FALSE= to avoid loading both the default and your own =rc.conf=. In this case you have to update your config manually though.

* Commands
:properties:
:header-args+: :tangle "ranger/.config/ranger/commands.py"
:end:

#+begin_src python
#+end_src

* Configuration
:properties:
:header-args+: :tangle "ranger/.config/ranger/rc.conf"
:end:

#+begin_src conf
#+end_src

* Rifle
:properties:
:header-args+: :tangle "ranger/.config/ranger/rifle.conf"
:end:

#+begin_src conf
#+end_src

* Scope
:properties:
:header-args+: :tangle "ranger/.config/ranger/scope.sh"
:header-args+: :tangle-mode (identity #o755)
:end:

#+begin_src sh
#+end_src
