#+title: vct's literate dotfiles
#+author: Victor Santos (vct)
#+keywords: dotfiles orgmode config

This is my dotfiles repo. I hope you find something useful here!

The files inside this repo should (ideally) contain all my public personal system configuration, structured within the [[http://www.literateprogramming.com/][Literate Programming]] methodology introduced by [[https://cs.stanford.edu/~knuth/][Donald Knuth]]. This setup allows me to migrate the configuration across different machines easily and, at the same time, understand why my settings are the way they are.

* Dependencies

The literate programming setup heavily depends on [[https://orgmode.org/][Org mode]] for [[https://orgmode.org/manual/Extracting-source-code.html][tangling]] the files. Therefore, it is almost mandatory to have [[https://www.gnu.org/software/emacs/][GNU Emacs]] installed to generate the configuration files without a hassle.

Tangling the files will result in a directory structure usable with [[https://www.gnu.org/software/stow/][GNU Stow]]. So, unless you want to be Spartan and manually create the symlinks, I recommend to install it.

* Instructions

Clone the repository in a folder in your =$HOME= (I keep it as a hidden directory =.dotfiles=):
#+begin_src sh
git clone https://gitlab.com/padawanphysicist/dotfiles.git ~/.dotfiles
#+end_src

then enter the directory,
#+begin_src sh
cd ~/.dotfiles
#+end_src

tangle the files (here I tangle all of them, but you can pick a single one if you like)
#+begin_src sh
for file in *.org ; do ./tangle -f ${file} ; done
#+end_src

and create the symlinks to your =$HOME= directory:
#+begin_src sh
for directory in */ ; do stow ${directory} ; done
#+end_src

* Configuration files

The configuration files written in literate style are:

#+begin_src sh :results raw :exports results
for file in *.org; do if [[ $file != "README.org" ]]; then echo '-' [[file:$file][$file]]; fi ; done
#+end_src

#+RESULTS:
- [[file:dunst.org][dunst.org]]
- [[file:emacs.org][emacs.org]]
- [[file:git.org][git.org]]
- [[file:pry.org][pry.org]]
- [[file:ranger.org][ranger.org]]
- [[file:redshift.org][redshift.org]]
- [[file:rofi.org][rofi.org]]
- [[file:shell.org][shell.org]]
- [[file:tmux.org][tmux.org]]
- [[file:xmonad.org][xmonad.org]]
- [[file:X.org][X.org]]
- [[file:xterm.org][xterm.org]]

Also, there is the folder [[file:misc][misc]], which contains dotfiles which are too small to worth write in Org, or I'm just too lazy to do it.
