#+TITLE: vct's dotfiles

This is my dotfiles repo. I hope you find something useful here!

* Dependencies

- [[https://www.gnu.org/software/stow/][GNU Stow]] for symlinking
- [[https://www.gnu.org/software/emacs/][GNU Emacs]] for tangling the files

* Instructions

Clone the repository in a folder in your =$HOME= (I keep it as a hidden directory =.dotfiles=), either from [[https://gitlab.com][GitLab]]
#+BEGIN_SRC sh
$ git clone https://github.com/padawanphysicist/dotfiles.git ~/.dotfiles
#+END_SRC

or [[https://github.com][GitHub]]:
#+BEGIN_SRC sh
$ git clone https://gitlab.com/padawanphysicist/dotfiles.git ~/.dotfiles
#+END_SRC

then enter the directory,
#+BEGIN_SRC sh
$ cd ~/.dotfiles
#+END_SRC

and link the important files to your =$HOME= directory:
#+BEGIN_SRC sh
$ ./bootstrap -i all # This will bootstrap all configuration process
#+END_SRC

** Selective installation

If you do not wish to install all files, you can select by category. For example, if you need to install only vim configuration, you can issue the command
#+BEGIN_SRC sh
$ ./bootstrap -i vim # Bootstrap configuration process for Vim only
#+END_SRC

* Configuration files

- [[bash.org]]: Bash configuration file.
- [[zsh.org][zsh.org]]: Zsh configuration file.
- [[vim.org]]: Vim configuration file.
- [[emacs.org]]: Emacs configuration file.
- [[tmux.org]]: Tmux configuration file.
- [[git.org]]: Git configuration file.

* Thanks

This setup is inspired by [[https://github.com/holman/dotfiles][holman's dotfiles]].
