#+title: vct's dotfiles

This is my dotfiles repo. I hope you find something useful here!

The files should contain all my (public) personal system configuration, structured within the [[http://www.literateprogramming.com/][Literate Programming]] methodology introduced by [[https://cs.stanford.edu/~knuth/][Donald Knuth]]. This setup allows me to migrate the configuration across different machines easily and, at the same time, understand why my settings are the way they are.

* Dependencies

The literate programming setup heavily depends on [[https://orgmode.org/][Org mode]] for [[https://orgmode.org/manual/Extracting-source-code.html][tangling]] the files. Therefore, it is almost mandatory to have [[https://www.gnu.org/software/emacs/][GNU Emacs]] installed to generate the configuration files without a hassle.

Tangling the files will result in a directory structure usable with [[https://www.gnu.org/software/stow/][GNU Stow]]. So, unless you want to be Spartan and manually create the symlinks, I recommend to install it.

* Instructions

Clone the repository in a folder in your =$HOME= (I keep it as a hidden directory =.dotfiles=):
#+begin_src sh
git clone https://gitlab.com/padawanphysicist/dotfiles.git ~/.dotfiles
#+end_src

then enter the directory,
#+begin_src sh
cd ~/.dotfiles
#+end_src

tangle the files
#+begin_src sh
for file in *.org ; do emacs --batch --eval "(progn (require 'org) (org-babel-tangle-file \"$file\"))"; done
#+end_src

and create the symlinks to your =$HOME= directory:
#+begin_src sh
for directory in */ ; do stow $directory ; done
#+end_src

* Configuration files

#+begin_src sh :results raw :exports results
for i in *.org; do if [[ $i != "README.org" ]]; then echo '-' [[$i]]; fi ; done
#+end_src

#+RESULTS:
- [[conky.org]]
- [[dunst.org]]
- [[emacs.org]]
- [[git.org]]
- [[openbox.org]]
- [[pry.org]]
- [[ranger.org]]
- [[redshift.org]]
- [[rofi.org]]
- [[shell.org]]
- [[tmux.org]]
- [[X.org]]
