* dotfiles
This is my dotfiles repo. I hope you find something useful here!

** Literate programming
Literate programming is a concept in which you write prose and embed in it source code. It has the benefit of being written for humans in the first place. I haven't spent enough time with it to know if this is true, but I suspect it also makes updating the documentation with a given change a little easier as well.

This is another attempt of mine for creating a readable and maintainable dotfiles configuration. I'm hopeful that using a literate programming style will help tame the (dis)organization.

For this I use the almighty [[http://orgmode.org][org-mode]], through the [[http://orgmode.org/worg/org-contrib/babel/intro.html][Babel project]]. Each .org file is /tangled/ out to the configuration file, and then linked to the destination in the home folder.

** Instructions
Clone the repository in a folder of your preference (here I will clone as `.dotfiles`), either from [[https://github.com][GitHub]],
#+begin_src sh
$ git clone https://github.com/padawanphysicist/dotfiles.git .dotfiles
#+end_src

or from [[https://gitlab.com][GitLab]]:
#+begin_src sh
$ git clone https://gitlab.com/padawanphysicist/dotfiles.git .dotfiles
#+end_src

then enter the directory,
#+begin_src sh
$ cd .dotfiles
#+end_src

and link the important files to your `$HOME` directory:
#+begin_src sh
$ ./bootstrap # this will symlink the important files
#+end_src
