* Tmux configuration

[[https://tmux.github.io/][tmux]] gives you terminal some superpowers.

** =.tmux.conf=
:PROPERTIES:
:TANGLE: tmux/tmux.conf
:PADLINE: no
:MKDIRP: yes
:END:

*** Changing prefix

The prefix is used to distinguish tmux commands from the commands sent to the programs inside of it. Following [[https://www.gnu.org/software/screen/][GNU Screen]] prefix, we change the default prefix to C-a.

First we release the default prefix...
#+BEGIN_SRC sh
unbind C-b
#+END_SRC

...and then we define a new prefix
#+BEGIN_SRC sh
set -g prefix C-a
bind-key C-a send-prefix
#+END_SRC

*** General options

**** Window indexing

Start window indexing at one instead of zero. Then it will be more like the keyboard layout
#+BEGIN_SRC sh
set -g base-index 1
setw -g pane-base-index 1
#+END_SRC

**** Window configuration

***** Bell

Ring the bell if any background window rang a bell
#+BEGIN_SRC sh
set -g bell-action any
#+END_SRC

***** 256 colors

#+BEGIN_SRC sh
set-option -g default-terminal "screen-256color"
#+end_src

***** Keybindings

Use emacs keybindings for tmux command line input.
#+BEGIN_SRC sh
set -gw status-keys emacs
#+END_SRC

Use vi keybindings in copy and choice modes
#+BEGIN_SRC sh
setw -g mode-keys vi
#+END_SRC

Setup 'v' to begin selection as in Vim
#+BEGIN_SRC sh
bind-key -t vi-copy v begin-selection
bind-key -t vi-copy y copy-pipe "xclip"
bind -n M-p run "tmux set-buffer \"$(xclip -o)\"; tmux paste-buffer"
#+END_SRC

Allows for faster key repetition
#+BEGIN_SRC sh
set -s escape-time 0
#+END_SRC

Rather than constraining window size to the maximum size of any client connected to the =session=, constrain window size to the maximum size of any client connected to =that window=. Much more reasonable.
#+BEGIN_SRC sh
setw -g aggressive-resize on
#+END_SRC

**** Pane switching

For pane switching it will be used the combination `Alt+<arrow key>`
#+BEGIN_SRC sh
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
#+END_SRC

In the case of multiple opened windows, you will get notified when something happens inside the other windows. The commands below will cause tmux to write a message and highlight the window inside of which the activity took place
#+BEGIN_SRC sh
setw -g monitor-activity on
set -g visual-activity on
#+END_SRC

Auto window rename
#+BEGIN_SRC sh
set-window-option -g automatic-rename
#+END_SRC

**** Pane management/navigation

Horizontal splits with `s` or `^S`
#+BEGIN_SRC sh
unbind s
unbind ^S
bind-key s split-window
bind-key ^S split-window
#+END_SRC

Vertical split with `v` or `^V`
#+BEGIN_SRC sh
unbind v
unbind ^V
bind-key v split-window -h
bind-key ^V split-window -h
#+END_SRC

Mouse mode on by default
#+BEGIN_SRC sh
set -g -q mouse on
#+END_SRC

Toggle mouse on/off
#+BEGIN_SRC sh
bind m \
    set -g -q mouse on \;\
    display 'Mouse: ON'
bind M \
    set -g -q mouse off \;\
    display 'Mouse: OFF'
#+END_SRC

copy-mode -e: This allows you to press page up in normal mode and have it scroll back into the history. If you page down back to the bottom of the history, it automatically exits copy mode. If there is an alternate screen (i.e. a full screen app like vim, less, mutt, etc) then it does not enter copy mode, but passes through the key press. This is because alternate screen apps usually handle page up/down itself and also will have no scroll back.
#+BEGIN_SRC sh
bind-key -T root PPage if-shell -F "#{alternate_on}" "send-keys PPage" "copy-mode -e; send-keys PPage"
bind-key -t vi-copy PPage page-up
bind-key -t vi-copy NPage page-down
#+END_SRC

Behaviour very similar to page up, except for the mouse wheel. i.e. I just scroll back and forward and if I scroll to the end of the history, copy mode automatically exits. Again, just pass through the click for alternate screens - they often handle the mouse themselves.
#+BEGIN_SRC sh
bind -n WheelUpPane   select-pane -t= \; copy-mode -e \; send-keys -M
bind -n WheelDownPane select-pane -t= \;                 send-keys -M
#+END_SRC

Left click on a window name in status bar to select it
#+BEGIN_SRC sh
bind -T root MouseDown1Status select-window -t= # default
#+END_SRC

Left click on a pane selects it
#+BEGIN_SRC sh
bind -T root MouseDown1Pane select-pane -t=
#+END_SRC

Draging on border resizes pane
#+BEGIN_SRC sh
bind -T root MouseDrag1Border resize-pane -M
#+END_SRC

Middle click on a window name in status bar to kill it
#+BEGIN_SRC sh
bind -T root MouseDown2Status kill-window
#+END_SRC

Middle click in a pane to paste
#+BEGIN_SRC sh
bind -T root MouseDown2Pane run -b "exec </dev/null; xclip -o | awk 1 ORS=' ' | tmux load-buffer - ; tmux paste-buffer"
#+END_SRC

**** Colors

Default statusbar colors
#+BEGIN_SRC sh
set-option -g status-bg colour235 #base02
set-option -g status-fg colour136 #yellow
set-option -g status-attr default
#+END_SRC

Default window title colors
#+BEGIN_SRC sh
set-window-option -g window-status-fg colour244 #base0
set-window-option -g window-status-bg default
#+END_SRC

Active window title colors
#+BEGIN_SRC sh
set-window-option -g window-status-current-fg colour166 #orange
set-window-option -g window-status-current-bg default
#+END_SRC

Active window style
#+BEGIN_SRC sh
set-window-option -g window-style 'bg=#181818'
set-window-option -g window-active-style 'bg=black'
set-window-option -g pane-active-border-style ''
#+END_SRC

Pane border
#+BEGIN_SRC sh
set-option -g pane-border-fg colour235 #base02
set-option -g pane-active-border-fg colour240 #base01
#+END_SRC

Message text
#+BEGIN_SRC sh
set-option -g message-bg colour235 #base02
set-option -g message-fg colour166 #orange
#+END_SRC

Pane number display
#+BEGIN_SRC sh
set-option -g display-panes-active-colour colour33 #blue
set-option -g display-panes-colour colour166 #orange
#+END_SRC

Clock
#+BEGIN_SRC sh
set-window-option -g clock-mode-colour green #green
#+END_SRC

*** Misc settings

#+BEGIN_SRC sh
set -g status-interval 1
set -g status-justify centre # center align window list
set -g status-left-length 20
set -g status-right-length 140
set -g status-left '#[fg=green]#H #[fg=black]• #[fg=green,bright]#(uname -r | cut -c 1-6)#[default]'
set -g status-right '#[fg=green,bg=default,bright]#(tmux-mem-cpu-load 1) #[fg=red,dim,bg=default]#(uptime | cut -f 4-5 -d " " | cut -f 1 -d ",") #[fg=white,bg=default]%a%l:%M:%S %p#[default] #[fg=blue]%Y-%m-%d'
#+END_SRC

Solves slight delay when switching modes in vim
#+BEGIN_SRC sh
set -sg escape-time 0
#+END_SRC

Open panel with the same folder as current panel
#+BEGIN_SRC sh
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
#+END_SRC

**** Powerline configuration

#+BEGIN_SRC sh
source ${HOME}/.local/lib/python3.5/site-packages/powerline/bindings/tmux/powerline.conf
#+END_SRC
