#+TITLE: Tmux configuration

[[https://tmux.github.io/][tmux]] gives you terminal some superpowers. Enough said.

#+CAPTION: Source listing for ~~/.tmux.conf~.
#+BEGIN_SRC conf :tangle tmux/.tmux.conf :noweb yes :mkdirp yes
<<tmux-config>>
#+END_SRC

* General settings
** Default terminal

Set the default terminal for new windows created in this session - the default value of the TERM environment variable. If you are using a 256 colour terminal, you will need to set the correct term in tmux. As of tmux 2.1, this is now ~tmux~, or ~tmux-256color~:

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
set-option -g default-terminal "tmux-256color"
#+END_SRC

** 24-bit color

tmux supports 24-bit color as of version 2.2. If your terminal supports 24-bit color (see this gist), add your terminal to the terminal-overrides setting. For example, if you use Termite, you would add: 

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
set -as terminal-overrides ',*:indn@'
#+END_SRC

** Pass keys through to its terminals

If this option is set, tmux will generate xterm-style function key sequences; these have a number included to indicate modifiers such as Shift, Alt or Ctrl.

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
setw -g xterm-keys on
#+END_SRC

** Fastest command sequences

Set the time in milliseconds for which tmux waits after an escape is input to determine if it is part of a function or meta key sequences. The default is 500 milliseconds.

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
set -s escape-time 0
#+END_SRC

** Increase repeat timeout

Allow multiple commands to be entered without pressing the prefix-key again in the specified time milliseconds (the default is 500). Whether a key repeats may be set when it is bound using the ~-r~ flag to bind-key. Repeat is enabled for the default keys bound to the resize-pane command.

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
set -sg repeat-time 600
#+END_SRC

** Set focus events

When enabled, focus events are requested from the terminal if supported and passed through to applications running in tmux. Attached clients should be detached and attached again after changing this option.

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
set -s focus-events on
#+END_SRC

** Changing prefix

The prefix is used to distinguish tmux commands from the commands sent to the programs inside of it. Following [[https://www.gnu.org/software/screen/][GNU Screen]] prefix, I change the default prefix to C-a.

We first release the default prefix,

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
unbind C-b
#+END_SRC

and then define a new prefix

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
set -g prefix C-a
bind-key C-a send-prefix
#+END_SRC

** Boost history

Set the maximum number of lines held in window history. This setting applies only to new windows - existing window histories are not resized and retain the limit at the point they were created.

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
set -g history-limit 10000
#+END_SRC

** Quickly reload tmux configuration

When you are playing around with your tmux config you often need to repeatedly open .tmux.conf file and then source it into the current tmux session.

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded!"
#+END_SRC

* Display
** Window indexing

Start window indexing at one instead of zero. Then it will be more like the keyboard layout

*** Start windows numbering at 1

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
set -g base-index 1
#+END_SRC

*** Make pane numbering consistent with windows

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
setw -g pane-base-index 1
#+END_SRC

*** Do not rename window to reflect current program

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
setw -g automatic-rename off
#+END_SRC

*** Renumber windows when a window is closed

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
set -g renumber-windows on
#+END_SRC

*** Set terminal title

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
set -g set-titles on
#set -g set-titles-string '#h ❐ #S ● #I #W'
set -g set-titles-string '#H:#S.#I.#P #W #T'
#+END_SRC

*** Slightly longer pane indicators display time

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
set -g display-panes-time 5000
#+END_SRC

*** Slightly longer status messages display time

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
set -g display-time 1000
#+END_SRC

*** Redraw status line every 10 seconds

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
set -g status-interval 10
#+END_SRC

*** Activity

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
set -g monitor-activity on
set -g visual-activity off
#+END_SRC

* Navigation
** Pane navigation
*** Open panel with the same folder as current panel

 #+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
bind c new-window -c "#{pane_current_path}"
 #+END_SRC

*** Horizontal splits with ~-~

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
unbind s
unbind ^S
unbind '"'
unbind -
bind - split-window -v -c "#{pane_current_path}"
#+END_SRC

*** Vertical split with ~\~

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
unbind v
unbind ^V
unbind %
unbind '\'
unbind '/'
bind \ split-window -h -c "#{pane_current_path}"
bind / split-window -h -c "#{pane_current_path}"
#+END_SRC

*** Mouse mode on by default

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
set -g -q mouse on
#+END_SRC

*** Toggle mouse on/off

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
bind m \
    set -g -q mouse on \;\
    display 'Mouse: ON'
bind M \
    set -g -q mouse off \;\
    display 'Mouse: OFF'
#+END_SRC

*** Pane switching

For pane switching it will be used the combination `Alt+<arrow key>`

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
#+END_SRC

*** Move to last active window

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
bind Tab last-window
#+END_SRC

*** Left click on a window name in status bar to select it

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
bind -T root MouseDown1Status select-window -t= 
#+END_SRC

*** Left click on a pane selects it

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
bind -T root MouseDown1Pane select-pane -t=
#+END_SRC

*** Dragging on border resizes pane

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
bind -T root MouseDrag1Border resize-pane -M
#+END_SRC

*** Middle click on a window name in status bar to kill it

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
bind -T root MouseDown2Status kill-window
#+END_SRC

*** Middle click in a pane to paste

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
bind -T root MouseDown2Pane run -b "exec </dev/null; xclip -o | awk 1 ORS=' ' | tmux load-buffer - ; tmux paste-buffer"
#+END_SRC

* Copy mode

Behaviour very similar to page up, except for the mouse wheel. i.e. I just scroll back and forward and if I scroll to the end of the history, copy mode automatically exits. Again, just pass through the click for alternate screens - they often handle the mouse themselves.

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
bind -n WheelUpPane   select-pane -t= \; copy-mode -e \; send-keys -M
bind -n WheelDownPane select-pane -t= \;                 send-keys -M
#+END_SRC

* Window configuration
** Bell

Ring the bell if any background window rang a bell

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
set -g bell-action any
#+END_SRC

** Keybindings
*** Use emacs keybindings for tmux command line input.

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
set -gw status-keys emacs
#+END_SRC

*** Use vi keybindings in copy and choice modes

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
setw -g mode-keys vi
#+END_SRC

*** Setup 'v' to begin selection as in Vim

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
bind-key -Tcopy-mode-vi 'v' send -X begin-selection
bind-key -Tcopy-mode-vi 'y' send -X copy-selection
bind -n M-p run "tmux set-buffer \"$(xclip -o)\"; tmux paste-buffer"
#+END_SRC

*** Aggressive resize

Rather than constraining window size to the maximum size of any client connected to the =session=, constrain window size to the maximum size of any client connected to =that window=. Much more reasonable.

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
setw -g aggressive-resize on
#+END_SRC

* Colors

This configuration was shamelessly stolen from [[http://www.hamvocke.com/blog/a-guide-to-customizing-your-tmux-conf/][here]]

** Panes

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
set -g pane-border-fg black
set -g pane-active-border-fg brightred
#+END_SRC

** Status bar design 
*** Status line

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
set -g status-justify left
set -g status-bg default
set -g status-fg colour12
set -g status-interval 2
#+END_SRC

*** Messaging

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
set -g message-fg black
set -g message-bg yellow
set -g message-command-fg blue
set -g message-command-bg black
#+END_SRC

*** Window mode

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
setw -g mode-bg colour6
setw -g mode-fg colour0
#+END_SRC

*** Window status

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
setw -g window-status-format " #F#I:#W#F "
setw -g window-status-current-format " #F#I:#W#F "
setw -g window-status-format "#[fg=magenta]#[bg=black] #I #[bg=cyan]#[fg=colour8] #W "
setw -g window-status-current-format "#[bg=brightmagenta]#[fg=colour8] #I #[fg=colour8]#[bg=colour14] #W "
setw -g window-status-current-bg colour0
setw -g window-status-current-fg colour11
setw -g window-status-current-attr dim
setw -g window-status-bg green
setw -g window-status-fg black
setw -g window-status-attr reverse
#+END_SRC

*** Info on left (I don't have a session display for now)

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
set -g status-left ''
#+END_SRC

*** Loud or quiet?

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
set-option -g visual-activity off
set-option -g visual-bell off
set-option -g visual-silence off
set-window-option -g monitor-activity off
#+END_SRC

*** The modes

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
setw -g clock-mode-colour colour135
setw -g mode-attr bold
setw -g mode-fg colour196
setw -g mode-bg colour238
#+END_SRC

*** The panes

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
set -g pane-border-bg colour235
set -g pane-border-fg colour238
set -g pane-active-border-bg colour236
set -g pane-active-border-fg colour51
#+END_SRC

*** The statusbar

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
set -g status-position bottom
set -g status-bg colour234
set -g status-fg colour137
set -g status-attr dim
set -g status-left ''
set -g status-right '#[bg=colour238,fg=colour155] #(check_internet) #[bg=colour248,fg=colour16] #[fg=colour166,bold]#(battery_percentage)#[fg=default]#[fg=colour16] (#[bg=colour248,fg=colour105]#(battery_state)#[fg=default]#[fg=colour16]) #[bg=colour238,fg=colour255] %d/%m/%Y %H:%M '
set -g status-right-length 50
set -g status-left-length 20

setw -g window-status-current-fg colour81
setw -g window-status-current-bg colour238
setw -g window-status-current-attr bold
setw -g window-status-current-format ' #I#[fg=colour250]:#[fg=colour255]#W#[fg=colour50]#F '

setw -g window-status-fg colour138
setw -g window-status-bg colour235
setw -g window-status-attr none
setw -g window-status-format ' #I#[fg=colour237]:#[fg=colour250]#W#[fg=colour244]#F '

setw -g window-status-bell-attr bold
setw -g window-status-bell-fg colour255
setw -g window-status-bell-bg colour1
#+END_SRC

*** The messages

#+BEGIN_SRC conf :noweb-ref tmux-config :noweb-sep "\n"
set -g message-attr bold
set -g message-fg colour232
set -g message-bg colour166
#+END_SRC


