#+title: X configuration

* X resources

*Xresources* is a user-level configuration dotfile, typically located at ~~/.Xresources~. It can be used to set the configuration parameters for X client applications like:
- configure terminal preferences (e.g. terminal colors)
- set DPI, anti-aliasing, hinting and other X font settings
- change the Xcursor theme
- theme *XScreenSaver*
- configure low-level X applications like: ~xorg-xclock~, ~xpdf~, ~xterm~

The file is structured as follows:

#+begin_src conf :tangle X/.Xresources :noweb yes :mkdirp yes
emacs.geometry: 100x40

<<xterm-configuration>>
<<rofi-configuration>>
#+end_src

** Xterm configuration

=xterm= is the standard terminal emulator for the X Window System. It is highly configurable and has many useful features.

The first thing I like to change is the default font. Also, I disable bold fonts:
#+begin_src conf :noweb-ref xterm-configuration
!XTerm*faceName: xft:Monego
!XTerm*faceSize: 15
XTerm*renderFont: true
XTerm*boldMode: false
#+end_src

Since I'm constantly changing the font size, it's interesting to change the font size using the keyboard. I've got a nice solution [[https://blog.rot13.org/2010/03/change-font-size-in-xterm-using-keyboard.html][here]].
#+begin_src conf :noweb-ref xterm-configuration
XTerm.VT100.translations: #override \
      Meta <Key> minus: smaller-vt-font() \n\
      Meta <Key> plus: larger-vt-font() \n\
      Meta <Key> KP_Subtract: smaller-vt-font() \n\
      Meta <Key> KP_Add: larger-vt-font() \n\
      Super <Key> minus: smaller-vt-font() \n\
      Super <Key> plus: larger-vt-font() \n\
      Super <Key> KP_Subtract: smaller-vt-font() \n\
      Super <Key> KP_Add: larger-vt-font() \n
#+end_src

The default colors are worth changing too!
#+begin_src conf :noweb-ref xterm-configuration
XTerm*background:#232629
XTerm*foreground:#cfcfc2
#+end_src

I put some keybindings to copy/paste in the terminal in a way similar to konsole:
#+begin_src conf :noweb-ref xterm-configuration
XTerm*VT100.Translations: #override \
      Shift Ctrl<Key>V: insert-selection(CLIPBOARD) \n\
      Shift Ctrl<Key>V: insert-selection(PRIMARY) \n\
      Shift<Btn1Down>: select-start() \n\
      Shift<Btn1Motion>: select-extend() \n\
      Shift<Btn1Up>: select-end(CLIPBOARD)
XTerm*selectToClipboard: true
#+end_src

Also, I *HATE* the audio bell. I like the visual bell much more:
#+begin_src conf :noweb-ref xterm-configuration
XTerm*visualBell: true
#+end_src

The rest of the options are summarized below:
#+begin_src conf :noweb-ref xterm-configuration
xterm*dynamicColors: true
XTerm*metaSendsEscape: true
XTerm*highlightSelection: true
XTerm*trimSelection: true
XTerm*scrollTtyOutput: false
#+end_src


