#+title: XMonad configuration
#+property: header-args  :mkdirp yes
#+property: header-args+ :tangle-mode (identity #o444)
#+property: header-args+ :noweb yes
#+property: header-args+ :tangle "xmonad/.xmonad/xmonad.hs"

[[https://xmonad.org/][XMonad]] is a dynamically tiling window manager written and configured in [[https://www.haskell.org/][Haskell]]. It allows you to get things done by automating the aligning and positioning of the windows you open.

* Import libraries

Most of the libraries used here come from the package =xmonad-contrib=.

#+begin_src haskell
-- Base
import XMonad
import System.Exit (exitSuccess)
import System.Directory
import qualified XMonad.StackSet as W
import GHC.IO.Handle.Types
import qualified Codec.Binary.UTF8.String as UTF8

-- Config
import XMonad.Config.Desktop -- desktopConfig

-- Hooks
import XMonad.Hooks.EwmhDesktops
import XMonad.Hooks.ManageDocks -- Automatically manage dock type programs (panel, mainly)
import XMonad.Hooks.DynamicLog -- For panel
import XMonad.Hooks.WorkspaceHistory
import XMonad.Hooks.FadeInactive -- Add transparency to inactive windows
import XMonad.Hooks.UrgencyHook

-- Util
import XMonad.Util.SpawnOnce
import XMonad.Util.Run -- For spawn
import XMonad.Util.EZConfig -- For custom keys
import XMonad.Util.NamedActions

-- Actions
import qualified XMonad.Actions.TreeSelect as TS
import XMonad.Actions.CopyWindow (kill1, killAllOtherCopies)
import XMonad.Actions.Promote
import XMonad.Actions.RotSlaves (rotSlavesDown, rotAllDown)
import XMonad.Actions.WithAll (sinkAll, killAll)
import XMonad.Actions.GroupNavigation

-- Layout
import XMonad.Layout.Spacing -- Add spacing (gaps) between windows
import XMonad.Layout.ToggleLayouts -- For toggling layouts
import XMonad.Layout.Grid -- For Grid layout
import XMonad.Layout.Renamed -- For renaming workspaces

-- Data
import qualified Data.Map as M
import Data.Char (isSpace, toUpper)
import Data.Monoid
import Data.Maybe (isJust)
import Data.Tree

-- Prompt
import XMonad.Prompt
import XMonad.Prompt.Input
import XMonad.Prompt.FuzzyMatch
import XMonad.Prompt.Man
import XMonad.Prompt.Pass
import XMonad.Prompt.Shell
import XMonad.Prompt.Ssh
import XMonad.Prompt.XMonad
import Control.Arrow (first)

-- DBUS
import qualified DBus as D
import qualified DBus.Client as D


--import Graphics.X11.ExtraTypes.XF86 -- For Brightness keys
--import System.IO (hClose)
--import System.Posix.Process(executeFile)
#+end_src

* Change prefix key

=modMask= lets you specify which modkey you want to use. The default is =mod1Mask= ("left Alt"). You may also consider using =mod3Mask= ("right Alt"), which does not conflict with emacs keybindings. I prefer the "windows key", which is usually =mod4Mask=.

#+begin_src haskell
vctModMask :: KeyMask
vctModMask = mod4Mask
#+end_src

* Custom Variables

Here I set some values for things like font, terminal and editor. With this I only have to change the value here to make modifications globally.

** Application launcher

#+begin_src haskell
vctLauncher :: String
vctLauncher = "rofi -sidebar-mode -modi 'run,drun,ssh' -show 'run'"
#+end_src

** Terminal

I like to be able to use the same terminal environment no matter which workspace I'm using. Therefore I always keep my terminal connected to a tmux session named =vct=.

#+begin_src haskell
vctTerminal :: String
-- vctTerminal = "st -e tmux attach -t vct"
vctTerminal = "xterm"
#+end_src

** Screensaver

#+begin_src haskell
vctScreenSaver :: String
vctScreenSaver = "xscreensaver-command -lock"
#+end_src

** Editor

#+begin_src haskell
vctEditor :: String
vctEditor = "emacsclient --create-frame --alternate-editor=''"
#+end_src

** Web browser

#+begin_src haskell
vctWebBrowser :: String
vctWebBrowser = "firefox"
#+end_src

** Width of Windows border

Change this to a value > 0 to have border:
#+begin_src haskell
vctBorderWidth :: Dimension
vctBorderWidth = 4
#+end_src

** Colors

*** Colorscheme

#+begin_src haskell
fg        = "#ebdbb2"
bg        = "#282828"
gray      = "#a89984"
bg1       = "#3c3836"
bg2       = "#505050"
bg3       = "#665c54"
bg4       = "#7c6f64"

green     = "#b8bb26"
darkgreen = "#98971a"
red       = "#fb4934"
darkred   = "#cc241d"
yellow    = "#fabd2f"
blue      = "#83a598"
purple    = "#d3869b"
aqua      = "#8ec07c"
white     = "#eeeeee"

pur2      = "#5b51c9"
blue2     = "#2266d0"
#+end_src

*** Set Border colors
The usual behaviour of XMonad for highlight the focused (active) window is to draw a (usually red) border around it. You can change the color and width of the borders as follows:

#+begin_src haskell
vctFocusedBorderColor :: String
vctFocusedBorderColor = "#5294E2"

vctNormalBorderColor :: String
vctNormalBorderColor = "#282c34"
#+end_src

* Workspaces

#+begin_src haskell
vctWorkspaces :: [String]
vctWorkspaces = ["1:WWW", "2:DEV", "3:READ", "4:AUX", "5:EXTRA"] ++ map show [6..9]
#+end_src

* Keybindings

#+begin_src haskell
vctKeys :: String -> [([Char], X ())]
vctKeys home =
  -- XMonad
  [ ("M-q", spawn "xmonad --restart") -- Recompiles XMonad
  , ("M-S-q", io exitSuccess)  -- Exits XMonad
  -- Programs
  , ("M-p", spawn vctLauncher)
  , ("M-a", spawn vctEditor)
  , ("M-z", sendMessage (Toggle "Full"))
  , ("M-S-z", spawn vctScreenSaver)
  -- Increase/decrease spacing (gaps)
  , ("M-d", decWindowSpacing 4)           -- Decrease window spacing
  , ("M-i", incWindowSpacing 4)           -- Increase window spacing
  , ("M-S-d", decScreenSpacing 4)         -- Decrease screen spacing
  , ("M-S-i", incScreenSpacing 4)         -- Increase screen spacing
  -- Kill windows
  , ("M-S-c", kill1)     -- Kill the currently focused client
  , ("M-S-a", killAll)   -- Kill all windows on current workspace
  -- Windows navigation
  , ("M-m", windows W.focusMaster)  -- Move focus to the master window
  , ("M-j", windows W.focusDown)    -- Move focus to the next window
  , ("M-k", windows W.focusUp)      -- Move focus to the prev window
  , ("M-S-m", windows W.swapMaster) -- Swap the focused window and the master window
  , ("M-S-j", windows W.swapDown)   -- Swap focused window with next window
  , ("M-S-k", windows W.swapUp)     -- Swap focused window with prev window
  , ("M-<Backspace>", promote)      -- Moves focused window to master, others maintain order
  , ("M-S-<Tab>", rotSlavesDown)    -- Rotate all windows except master and keep focus in place
  , ("M-C-<Tab>", rotAllDown)       -- Rotate all the windows in the current stack
  , ("M1-<Tab>", spawn "rofi -modi window -show window")
  -- Tree Select
  --, ("C-M1-<Delete>", treeselectAction tsDefaultConfig)
  , ("C-M1-<Delete>", spawn "rofi -show powermenu -modi powermenu:rofi-power-menu")
  , ("M-S-<Space>", spawn "rofi -show kbd -modi kbd:rofi-switch-kbd-layout")
  ]
#+end_src

* Log Hooks

xmonad calls the =logHook= with every internal state update, which is useful for (among other things) outputting status information to an external status bar program such as xmobar or polybar.

** Transparency to inactive windows


However, there is a neater way to do this: make the unfocused (inactive) windows transparent. However, in order to do this, you must install a compositor, like Compton of xcompmgr. For now I'm sticking to [[https://github.com/chjj/compton][compton]], by eventually I'll try [[https://github.com/yshui/picom][picom]], which is a fork being activelly maintained.

#+begin_src haskell
vctTransparentInactive :: X()
vctTransparentInactive = fadeInactiveLogHook fadeAmount
    where fadeAmount = 0.7
#+end_src

** Log hook for polybar

#+begin_src haskell
myLogHook :: D.Client -> PP
myLogHook dbus = def
    { ppOutput = dbusOutput dbus
    , ppCurrent = wrap ("%{F" ++ blue2 ++ "} ") " %{F-}"
    , ppVisible = wrap ("%{F" ++ blue ++ "} ") " %{F-}"
    , ppUrgent = wrap ("%{F" ++ red ++ "} ") " %{F-}"
    , ppHidden = wrap " " " "
    , ppWsSep = ""
    , ppSep = " | "
    , ppTitle = myAddSpaces 25
    }

-- Emit a DBus signal on log updates
dbusOutput :: D.Client -> String -> IO ()
dbusOutput dbus str = do
    let signal = (D.signal objectPath interfaceName memberName) {
            D.signalBody = [D.toVariant $ UTF8.decodeString str]
        }
    D.emit dbus signal
  where
    objectPath = D.objectPath_ "/org/xmonad/Log"
    interfaceName = D.interfaceName_ "org.xmonad.Log"
    memberName = D.memberName_ "Update"

myAddSpaces :: Int -> String -> String
myAddSpaces len str = sstr ++ replicate (len - length sstr) ' '
  where
    sstr = shorten len str
#+end_src

** Combine hooks

#+begin_src haskell
vctLogHook h = vctTransparentInactive <+> (dynamicLogWithPP (myLogHook h)) <+> historyHook
#+end_src

* Manage Hooks

Send applications to the right workspace

#+begin_src haskell
vctManageHook :: ManageHook
vctManageHook = composeAll
    [ manageDocks --, className =? "Firefox" --> doShift "1:WWW"
    ]
#+end_src

* Layouts
** Tall
The Tall layout has the master pane on the left, taking half of the screen. All other windows share the right half of the screen, and are stacked vertically, top to bottom.

This my the go-to layout, meant to be the first one that you get when running xmonad. It's common to have one window in focus while a couple secondary windows are in view, so the Tall layout works great. It's very useful in many situations, but the windows on the right start to feel a little crowded beyond five windows.

#+begin_src haskell
vctLayoutTall = Tall 1 (3/100) (7/10)
#+end_src

** Layout mirror

Mirrored version of =Tall=.

#+begin_src haskell
vctLayoutMirror = Mirror (Tall 1 (3/100) (3/5))
#+end_src

** Create hook

#+begin_src haskell
vctLayoutHook = renamed [CutWordsLeft 1] $ spacingRaw True (Border 0 10 10 10) True (Border 10 10 10 10) True $ toggleLayouts Full vctLayoutTall ||| vctLayoutMirror ||| Full
#+end_src

* Startup hook

These are commands we want XMonad to execute on startup or is restarted with =mod-q=.
#+begin_src haskell
vctStartupHook :: X()
vctStartupHook = do
  -- Set wallpaper
  spawnOnce "~/.fehbg &"
  -- Set cursor
  spawnOnce "xsetroot -cursor_name left_ptr &"
  -- Use caps as an additional Ctrl (useful for emacs)
  -- spawnOnce "setxkbmap -layout br -option -option altwin:meta_alt -option ctrl:nocaps &" -- ABNT2 Layout
  spawnOnce "setxkbmap us -variant intl &" -- ABNT2 Layout
  -- Compositing
  spawnOnce "picom --experimental-backend &"
  -- Notifications
  spawnOnce "dunst &"
  -- Start tmux in server mode
  spawnOnce "tmux new-session -d -s vct &"
  -- Start Emacs in server mode
  spawnOnce "emacs --daemon &"
  -- Start systemtray
  spawnOnce "stalonetray &"
  -- Start clipboard manager
  spawnOnce "klipper &"
  -- Start dropbox
  spawnOnce "dropbox start &"
  -- Start screensaver daemon
  spawnOnce "xscreensaver -no-splash &"
  -- Show notification in the end
  spawn "notify-send -i \"emblem-important-symbolic\" \"XMonad started\""
  -- Start Polybar
  spawn "~/.config/polybar/launch.sh"
#+end_src

* Run XMonad

Now we run xmonad with all the settings we defined previously:
#+begin_src haskell
main :: IO()
main = do
  home <- getHomeDirectory
  dbus <- D.connectSession
  -- Request access to the DBus name
  D.requestName dbus (D.busName_ "org.xmonad.Log")
      [D.nameAllowReplacement, D.nameReplaceExisting, D.nameDoNotQueue]
  xmonad
    $ withUrgencyHook NoUrgencyHook
    $ ewmh
    $ docks
    $ desktopConfig
    { modMask = vctModMask
    , terminal = vctTerminal
    , borderWidth        = vctBorderWidth
    , workspaces         = vctWorkspaces
    , normalBorderColor  = vctNormalBorderColor
    , focusedBorderColor = vctFocusedBorderColor
    , manageHook         = vctManageHook <+> manageDocks <+> manageHook desktopConfig
    , layoutHook         = avoidStruts $ vctLayoutHook
    , handleEventHook    = fullscreenEventHook <+> handleEventHook desktopConfig
    , startupHook        = vctStartupHook
    , logHook = workspaceHistoryHook <+> (vctLogHook dbus)
    } `additionalKeysP` vctKeys home
#+end_src

#+begin_src haskell
--main :: IO()
--main = do
--  home <- getHomeDirectory
--  xmproc0 <- spawnPipe "xmobar -x 0 $HOME/.config/xmobar/xmobarrc"
--  xmonad
--    $ withUrgencyHook NoUrgencyHook
--    $ ewmh
--    $ desktopConfig
--    { modMask = vctModMask
--    , terminal = vctTerminal
--    , borderWidth        = vctBorderWidth
--    , workspaces         = myClickableWorkspaces
--    , normalBorderColor  = vctNormalBorderColor
--    , focusedBorderColor = vctFocusedBorderColor
--    , manageHook         = vctManageHook <+> manageHook desktopConfig
--    , layoutHook         = avoidStruts $ vctLayoutHook
--    , startupHook        = vctStartupHook
--    , logHook = workspaceHistoryHook <+> (vctLogHook xmproc0)
--    } `additionalKeysP` vctKeys home
#+end_src

* Xmobar configuration                                             :optional:
:properties:
:header-args+: :tangle "xmonad/.config/xmobar/xmobarrc"
:end:

You would like to install/enable [[https://elpa.gnu.org/packages/rainbow-mode.html][rainbow-mode]] to see the colors here =)

#+begin_src haskell
-- http://projects.haskell.org/xmobar/
-- install xmobar with these flags: --flags="with_alsa" --flags="with_mpd" --flags="with_xft"  OR --flags="all_extensions"
-- you can find weather location codes here: http://weather.noaa.gov/index.html

Config { font    = "xft:Droid Sans Mono Slashed for Powerline:pixelsize=17:antialias=true:hinting=true"
       , additionalFonts = ["xft:Mononoki Nerd Font:pixelsize=18:antialias=true:hinting=true", "xft:Mononoki Nerd Font:pixelsize=20:antialias=true:hinting=true", "xft:Font Awesome 5 Free Regular:size=16", "xft:Font Awesome 5 Free Solid:size=16", "xft:Font Awesome 5 Brands Regular:size=16"] -- For the icons
       , bgColor = "#282c34"
       , fgColor = "#999999"
       -- , position = BottomW L 100
       , position = Static { xpos = 0, ypos = 1055, width = 1880, height = 25 }
       , lowerOnStart = True
       , hideOnStart = False
       , allDesktops = True
       , persistent = True
       , iconRoot = "/home/santos/.xmonad/xpm/"  -- default: "."
       , commands = [
                      -- Time and date
                      Run Date "<icon=calendar-clock-icon_20.xpm/> %b %d %Y - %H:%M" "date" 50
                    , Run Com "uptime" ["-p"] "" 36000
                      -- Network up and down
                    , Run Network "wlp2s0" ["-t", "<icon=net_up_20.xpm/> <rx>kb <icon=net_down_20.xpm/> <tx>kb"] 20
                      -- Cpu usage in percent
                    , Run MultiCpu       ["-w", "2" -- Fix width of the field
                                         , "-c", "0"-- Padding with zeros
                                         , "--template" , "<total0>% • <total1>% • <total2>% • <total3>%"
                                         , "--Low"      , "50"         -- units: %
                                         , "--High"     , "85"         -- units: %
                                         , "--low"      , "green"
                                         , "--normal"   , "orange"
                                         , "--high"     , "red"
                                         ] 10
                      -- Ram used number and percent
                    --, Run Memory ["-t", "RAM: <used>M (<usedratio>%)"] 20
                    , Run Memory ["-w", "2", "-c", "0", "-t", "<fc=#5294E2>RAM</fc>: <usedratio>%"] 10
                    , Run Swap ["-w", "2", "-c", "0", "-t", "<fc=#5294E2>SWAP</fc>: <usedratio>%"] 10
                      -- Disk space free
                    , Run DiskU [("/", "<fc=#5294E2>HD</fc>: <free> free")] [] 60
                      -- Runs a standard shell command 'uname -r' to get kernel version
                    , Run Com "uname" ["-r"] "" 3600
                      -- Prints out the left side items such as workspaces, layout, etc.
                      -- The workspaces are 'clickable' in my configs.
                    , Run UnsafeStdinReader
                    ]
       , sepChar = "%"
       , alignSep = "}{"
       , template = "<action=`xdotool key ctrl+alt+Delete`> <icon=haskell_20.xpm/> </action><fn=2>|</fn> %UnsafeStdinReader% <fn=2>|</fn> <icon=cpu_20.xpm/> %multicpu%<fn=2> | </fn>%uptime% <fn=2>|</fn> <icon=memory-icon_20.xpm/> %memory% • %swap%<fn=2> |</fn> <icon=harddisk-icon_20.xpm/> %disku%}{<fc=#98be65>%wlp2s0%</fc><fn=2>|</fn> %date% "
       }
#+end_src

* System tray :optional:
:properties:
:header-args+: :tangle "xmonad/.stalonetrayrc"
:end:

#+begin_src conf
decorations none
transparent false
dockapp_mode none
geometry 1x1-20+1055
background "#282c34"
kludges force_icons_size
grow_gravity NW
icon_gravity NW
icon_size 25
sticky true
#window_strut none
window_type dock
window_layer bottom
no_shrink false
skip_taskbar true
#+end_src
* Polybar configuration
** Launcher
:properties:
:header-args+: :tangle "xmonad/.config/polybar/launch.sh"
:header-args+: :tangle-mode (identity #o755)
:end:

#+begin_src bash
#!/bin/bash

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch Polybar, using default config location ~/.config/polybar/config
polybar panel &

echo "Polybar launched..."
#+end_src

** Bar configuration
:properties:
:header-args+: :tangle "xmonad/.config/polybar/config"
:end:

#+begin_src conf
;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
;background = ${xrdb:color0:#222}
background = #222
background-alt = #444
;foreground = ${xrdb:color7:#222}
foreground = #dfdfdf
foreground-alt = #555
primary = #ffb52a
secondary = #e60053
alert = #bd2c40

[bar/panel]
;monitor = ${env:MONITOR:HDMI-1}
width = 100%
height = 27
;offset-x = 1%
;offset-y = 1%
;radius = 6.0
fixed-center = true
bottom = true
override-redirect = false

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3
line-color = #f00

border-size = 4
border-color = #00000000

padding-left = 0
padding-right = 2

module-margin-left = 1
module-margin-right = 2

font-0 = Fira Mono:pixelsize=13;1
font-1 = Font Awesome 5 Free Solid:pixelsize=13;1
font-2 = Font Awesome 5 Brands Regular:pixelsize=13;1
font-3 = Font Awesome 5 Free Regular:pixelsize=13;1

modules-left = xmonad
modules-center = 
modules-right = cpu memory pulseaudio wlan xkeyboard date

tray-position = right
tray-padding = 2

cursor-click = pointer
cursor-scroll = ns-resize

[module/xmonad]
type = custom/script
exec = xmonad-log
tail = true

[module/date]
type = internal/date
interval = 5
date = " %Y-%m-%d"
date-alt = 
time = "%H:%M "
time-alt = 
format-prefix = ""
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #0a6cf5
label = %date% %time%

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-prefix-underline = ${colors.secondary}
label-layout = %layout%
label-layout-underline = ${colors.secondary}
label-indicator-padding = 1
label-indicator-margin = 1
label-indicator-background = ${colors.secondary}
label-indicator-underline = ${colors.secondary}

[module/wlan]
type = internal/network
format-prefix = ""
interface = wlp2s0
interval = 3.0
format-connected =   <label-connected>
format-disconnected = 睊 <label-disconnected>
format-connected-underline = #9f78e1
label-connected = %essid% %downspeed:6%
label-disconnected = not connected

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "  "
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #f90000
label = %percentage-core1:2%% %percentage-core2:2%% %percentage-core3:2%% %percentage-core4:2%%

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #4bffdc
label = %percentage_used%%

[module/pulseaudio]
type = internal/pulseaudio
format-volume = <label-volume>
label-volume =  %percentage%%
label-volume-foreground = ${root.foreground}
format-muted = <label-muted>
label-muted =  muted
label-muted-foreground = #666

[module/battery]
type = internal/battery
battery = BAT0
adapter = AC
full-at = 98
format-charging = <animation-charging> <label-charging>
format-charging-underline = #ffb52a
format-discharging = <animation-discharging> <label-discharging>
format-discharging-underline = ${self.format-charging-underline}
format-full-prefix = " "
format-full-prefix-foreground = ${colors.foreground-alt}
format-full-underline = ${self.format-charging-underline}
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-foreground = ${colors.foreground-alt}
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-foreground = ${colors.foreground-alt}
animation-charging-framerate = 750
animation-discharging-0 = 
animation-discharging-1 = 
animation-discharging-2 = 
animation-discharging-foreground = ${colors.foreground-alt}
animation-discharging-framerate = 750

[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 60

format = <ramp> <label>
format-underline = #f50a4d
format-warn = <ramp> <label-warn>
format-warn-underline = ${self.format-underline}

label = %temperature-c%
label-warn = %temperature-c%
label-warn-foreground = ${colors.secondary}

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-foreground = ${colors.foreground-alt}

[settings]
screenchange-reload = true
;compositing-background = xor
;compositing-background = screen
;compositing-foreground = source
;compositing-border = over
;pseudo-transparency = false

[global/wm]
margin-top = 5
margin-bottom = 5
#+end_src
