#+title: XTerm configuration
#+property: header-args  :mkdirp yes
#+property: header-args+ :tangle-mode (identity #o644)
#+property: header-args+ :noweb yes
#+property: header-args+ :padline no
#+property: header-args+ :tangle "xterm/.Xresources.d/xterm"

[[https://invisible-island.net/xterm/][xterm]] is the standard terminal emulator for the X Window System. It is highly configurable and has many useful features, although the defaults make it look like crap. Here is some configuration to make it behave in a more pleasant way.

* General settings
** Enable color support

This sets the =TERM= environment variable:
#+begin_src conf
XTerm.termName: xterm-256color
#+end_src

** Disable audio bell

I *HATE* the audio bell. I like the visual bell much more!
#+begin_src conf
XTerm*visualBell: true
#+end_src

** Set locale

Force xterm to more strictly follow your locale:
#+begin_src conf
XTerm.vt100.locale: true
#+end_src

** Enable TrueType fonts

#+begin_src conf
XTerm*renderFont: true
#+end_src

** Disable bold text

I dislike bold faces, they look too visually noisy.
#+begin_src conf
XTerm*boldMode: false
#+end_src

** Make XTerm recognize escape sequence to change colors

#+begin_src conf
xterm*dynamicColors: true
#+end_src

** Make 'Alt' key behave as on other terminal emulators

The default =Alt= key behavior in xterm is a modifier to send eight bit input characters e.g. to insert =æ= by pressing =Alt+f=. To make =Alt= instead send a =^[= (escape) key (as in gnome-terminal and konsole), set

#+begin_src conf
XTerm*metaSendsEscape: true
#+end_src

* Set font face and size
** Font face

#+begin_src conf
XTerm*faceName: xft:Monego
XTerm*faceSize: 9
#+end_src

** Font sizes

The sizes defined here are used when resizing the font, either from the menu or from the keyboard keybinding:
#+begin_src conf
! VT Font Menu: Unreadable
XTerm*faceSize1: 9
! VT Font Menu: Tiny
XTerm*faceSize2: 11
! VT Font Menu: Small
XTerm*faceSize3: 13
! VT Font Menu: Medium
XTerm*faceSize4: 17
! VT Font Menu: Large 
XTerm*faceSize5: 19
! VT Font Menu: Huge
XTerm*faceSize6: 21
#+end_src

* Scrollbar behaviour
** Hide scrollbar

#+begin_src conf
XTerm*scrollBar: false
#+end_src

** Do not scroll when there is new input

#+begin_src conf
XTerm*scrollTtyOutput: false
#+end_src

** Lines of output you can scroll back over

Default value is 1024.
#+begin_src conf
XTerm*scrollLines: 15000
#+end_src

* Text selection
** Highlight selection

#+begin_src conf
XTerm*highlightSelection: true
#+end_src

** Remove trailing spaces from selection

#+begin_src conf
XTerm*trimSelection: true
#+end_src

** Selection copy to clipboard

#+begin_src conf
XTerm*selectToClipboard: true
#+end_src

* Key bindings

Default xterm keybindings can overriden using =XTerm*VT100.translations=:
#+begin_src conf
XTerm*VT100.translations: #override \
      <<kbd-navigation>>
      <<kbd-fontsize>>
      <<kbd-copy-paste>>
#+end_src

** Make =Home= scroll to the top and =End= to the bottom

#+begin_src conf :noweb-ref kbd-navigation :tangle no
<KeyPress> Home:  scroll-to(begin) \n\
<KeyPress> End:   scroll-to(end)   \n\
#+end_src

** Move up/down with PgUp/PgDown

#+begin_src conf :noweb-ref kbd-navigation :tangle no
<KeyPress> Prior: scroll-back(1,page) \n\
<KeyPress> Next:  scroll-forw(1,page) \n\
#+end_src

** Change fontsize

Since I'm constantly changing the font size, it's interesting to change the font size using the keyboard. I've got a nice solution [[https://blog.rot13.org/2010/03/change-font-size-in-xterm-using-keyboard.html][here]].
#+begin_src conf :noweb-ref kbd-fontsize :tangle no
Ctrl Shift <Key> minus: smaller-vt-font()       \n\
Ctrl Shift <Key> plus: larger-vt-font()         \n\
Ctrl Shift <Key> KP_Subtract: smaller-vt-font() \n\
Ctrl Shift <Key> KP_Add: larger-vt-font()       \n\
Ctrl <Key> 0: set-vt-font(d)                    \n\
#+end_src

** Copy/Paste

I put some keybindings to copy/paste in the terminal in a way similar to konsole:

#+begin_src conf :noweb-ref kbd-copy-paste :tangle no
Shift Ctrl <Key>C: copy-selection(CLIPBOARD) \n\
Shift Ctrl <Key>V: insert-selection(CLIPBOARD) \n\
Shift<Btn1Down>: select-start() \n\
Shift<Btn1Motion>: select-extend() \n\
Shift<Btn1Up>: select-end(CLIPBOARD)
#+end_src

* Basic colors

#+begin_src conf
XTerm*foreground: #d8dee9
XTerm*background: #2e3440
#+end_src

