#!/usr/bin/env bash

__usage_msg="
Run terminal emulator with light/dark theme

Usage: ${__base} [-h | -l | -d ]

  -h, --help    Show this message
  -l, --light   Set light theme
  -d, --dark    Set dark theme
"

help() {
    echo "${__usage_msg}"
    exit 0
}

LIGHT_THEME=${XRESOURCES_LIGHT_THEME:-base16-solarized-light}
DARK_THEME=${XRESOURCES_DARK_THEME:-nord}

xrdb -load ~/.Xresources

opt="${1:-}"
case "${opt}" in
    -h | --help)
        help
        ;;
    -l | --light)
        xrdb -merge ~/.Xresources.d/${LIGHT_THEME}.Xresources
        ;;
    -d | --dark)
        xrdb -merge ~/.Xresources.d/${DARK_THEME}.Xresources
        ;;
    *)
        help
        ;;
esac

xterm 
