* Tmux configuration

** Changing prefix

The prefix is used to distinguish tmux commands from the commands sent to the programs inside of it. Following GNU Screen prefix, we change the default prefix to =C-a=.

First we release the default prefix...
#+begin_src sh :tangle tmux.conf.symlink
unbind C-b
#+end_src

...and then we define a new prefix
#+begin_src sh :tangle tmux.conf.symlink
set -g prefix C-a
bind-key C-a send-prefix
#+end_src

** General options

*** Window indexing

Start window indexing at one instead of zero. Then it will be more like the keyboard layout
#+begin_src sh :tangle tmux.conf.symlink
set -g base-index 1
setw -g pane-base-index 1
#+end_src

Ring the bell if any background window rang a bell
#+begin_src sh :tangle tmux.conf.symlink
set -g bell-action any
#+end_src

Fix weird behaviour on vim colors in solarized theme
#+begin_src sh :tangle tmux.conf.symlink
set -g default-terminal "screen-256color"
#+end_src

Use vi keybindings for tmux commandline input. Note that to get command mode you need to hit ESC twice&#x2026;
#+begin_src sh :tangle tmux.conf.symlink
set -g status-keys emacs
#+end_src

Use vi keybindings in copy and choice modes
#+begin_src sh :tangle tmux.conf.symlink
setw -g mode-keys vi
#+end_src

Status bar
#+begin_src sh :tangle tmux.conf.symlink
set-option -g status-utf8 on
#+end_src

Allows for faster key repetition
#+begin_src sh :tangle tmux.conf.symlink
set -s escape-time 0
#+end_src

Rather than constraining window size to the maximum size of any client connected to the =session=, constrain window size to the maximum size of any client connected to =that window=. Much more reasonable.
#+begin_src sh :tangle tmux.conf.symlink
setw -g aggressive-resize on
#+end_src

**** Pane switching

For pane switching it will be used the combination `Alt+<arrow key>`
#+begin_src sh :tangle tmux.conf.symlink
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
#+end_src

In the case of multiple opened windows, you will get notified when something happens inside the other windows. The commands below will cause tmux to write a message and highlight the window inside of which the activity took place
#+begin_src sh :tangle tmux.conf.symlink
setw -g monitor-activity on
set -g visual-activity on
#+end_src

Auto window rename
#+begin_src sh :tangle tmux.conf.symlink
set-window-option -g automatic-rename
#+end_src

Use utf8
#+begin_src sh :tangle tmux.conf.symlink
set -g utf8
set-window-option -g utf8 on
#+end_src
*** Pane management/navigation

Horizontal splits with =s= or =^S=
#+begin_src sh :tangle tmux.conf.symlink
unbind s
unbind ^S
bind-key s split-window
bind-key ^S split-window
#+end_src

Vertical split with `v` or `^V`
#+begin_src sh :tangle tmux.conf.symlink
unbind v
unbind ^V
bind-key v split-window -h
bind-key ^V split-window -h
#+end_src

Mouse mode
#+begin_src sh :tangle tmux.conf.symlink
set -g mode-mouse off
set -g mouse-resize-pane on
set -g mouse-select-pane on
set -g mouse-select-window on
#+end_src

Toggle mouse on
#+begin_src sh :tangle tmux.conf.symlink
bind m \
    set -g mode-mouse on \;\
    set -g mouse-resize-pane on \;\
    set -g mouse-select-pane on \;\
    set -g mouse-select-window on \;\
    display 'Mouse: ON'

bind M \
    set -g mode-mouse off \;\
    set -g mouse-resize-pane off \;\
    set -g mouse-select-pane off \;\
    set -g mouse-select-window off \;\
    display 'Mouse: OFF'
#+end_src

*** Colors

Default statusbar colors
#+begin_src sh :tangle tmux.conf.symlink
set-option -g status-bg colour235 #base02
set-option -g status-fg colour136 #yellow
set-option -g status-attr default
#+end_src

Default window title colors
#+begin_src sh :tangle tmux.conf.symlink
set-window-option -g window-status-fg colour244 #base0
set-window-option -g window-status-bg default
#+end_src

Active window title colors
#+begin_src sh :tangle tmux.conf.symlink
set-window-option -g window-status-current-fg colour166 #orange
set-window-option -g window-status-current-bg default
#+end_src

Pane border
#+begin_src sh :tangle tmux.conf.symlink
set-option -g pane-border-fg colour235 #base02
set-option -g pane-active-border-fg colour240 #base01
#+end_src

Message text
#+begin_src sh :tangle tmux.conf.symlink
set-option -g message-bg colour235 #base02
set-option -g message-fg colour166 #orange
#+end_src

Pane number display
#+begin_src sh :tangle tmux.conf.symlink
set-option -g display-panes-active-colour colour33 #blue
set-option -g display-panes-colour colour166 #orange
#+end_src

Clock
#+begin_src sh :tangle tmux.conf.symlink
set-window-option -g clock-mode-colour green #green
#+end_src

Misc settings
#+begin_src sh :tangle tmux.conf.symlink
set -g status-interval 1
set -g status-justify centre # center align window list
set -g status-left-length 20
set -g status-right-length 140
set -g status-left '#[fg=green]#H #[fg=black]• #[fg=green,bright]#(uname -r | cut -c 1-6)#[default]'
set -g status-right '#[fg=green,bg=default,bright]#(tmux-mem-cpu-load 1) #[fg=red,dim,bg=default]#(uptime | cut -f 4-5 -d " " | cut -f 1 -d ",") #[fg=white,bg=default]%a%l:%M:%S %p#[default] #[fg=blue]%Y-%m-%d'
#+end_src

Solves slight delay when switching modes in vim
#+begin_src sh :tangle tmux.conf.symlink
set -sg escape-time 0
#+end_src

Open panel with the same folder as current panel
#+begin_src sh :tangle tmux.conf.symlink
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
#+end_src






# Local Variables:
# mode: org
# End:
