#+title: TMUX configuration
#+author: Victor Santos (vct)
#+email: victor.phb@gmail.com

* Changing  prefix 
  The prefix is used to distinguish tmux commands from the commands sent to
  the programs inside of it. Following GNU Screen prefix, we change the
  default prefix to C-a.

  First we release the default prefix
  #+name: startup
  #+begin_src shell-script 
  unbind C-b  # Release the default prefix
  #+end_src
  and then we define a new prefix:
  #+name: startup
  #+begin_src shell-script 
  set -g prefix C-a
  bind-key C-a send-prefix 
  #+end_src

* General options 
  Start window indexing at one instead of zero. Then it will be more like
  the keyboard layout
  #+name: general-options
  #+begin_src shell-script
  set -g base-index 1
  setw -g pane-base-index 1
  #+end_src

  Ring the bell if any background window rang a bell
  #+name: general-options
  #+begin_src shell-script
  set -g bell-action any
  #+end_src

  Fix weird behaviour on vim colors in solarized theme
  #+name: general-options
  #+begin_src shell-script
  set -g default-terminal "screen-256color"
  #+end_src

  Scrollback size
  #+name: general-options
  #+begin_src
  set -g history-limit 10000
  #+end_src

  Use vi keybindings for tmux commandline input.
  Note that to get command mode you need to hit ESC twice...
  #+name: general-options
  #+begin_src shell-script
  set -g status-keys emacs
  #+end_src
  
  Use vi keybindings in copy and choice modes
  #+name: general-options
  #+begin_src shell-script
  setw -g mode-keys vi
  #+end_src
  
  status bar
  #+name: general-options
  #+begin_src shell-script
  set-option -g status-utf8 on
  #+end_src

  Allows for faster key repetition
  #+name: general-options
  #+begin_src shell-script
  set -s escape-time 0
  #+end_src

  Rather than constraining window size to the maximum size of any client
  connected to the *session*, constrain window size to the maximum size of any
  client connected to *that window*. Much more reasonable.
  #+name: general-options
  #+begin_src shell-script
  setw -g aggressive-resize on
  #+end_src

** Pane switching
   For pane switching it will be used the combination Alt+<arrow key>
   #+name: general-options
   #+begin_src shell-script
   bind -n M-Left select-pane -L
   bind -n M-Right select-pane -R
   bind -n M-Up select-pane -U
   bind -n M-Down select-pane -D
   #+end_src

** Activity monitoring
   In the case of multiple opened windows, you will get notified when something
   happens inside the other windows. The commands below will cause tmux to
   write a message and highlight the window inside of which the activity took
   place
   #+name: general-options
   #+begin_src shell-script
   setw -g monitor-activity on
   set -g visual-activity on
   #+end_src
** auto window rename
   #+name: general-options
   #+begin_src shell-script
   set-window-option -g automatic-rename
   #+end_src

** use utf8
   #+name: general-options
   #+begin_src shell-script
   set -g utf8
   set-window-option -g utf8 on
   #+end_src

* Pane management / navigation

** Horizontal splits with s or ^S
   #+name: general-options
   #+begin_src shell-script
   unbind s
   unbind ^S
   bind-key s split-window
   bind-key ^S split-window
   #+end_src

** Vertical split with v or ^V
   #+name: general-options
   #+begin_src shell-script
   unbind v
   unbind ^V
   bind-key v split-window -h
   bind-key ^V split-window -h
   #+end_src

* Mouse mode
   #+name: general-options
   #+begin_src shell-script
   set -g mode-mouse on
   set -g mouse-resize-pane on
   set -g mouse-select-pane on
   set -g mouse-select-window on
   #+end_src

** Toggle mouse on
   #+name: general-options
   #+begin_src shell-script
   bind m \
       set -g mode-mouse on \;\
       set -g mouse-resize-pane on \;\
       set -g mouse-select-pane on \;\
       set -g mouse-select-window on \;\
       display 'Mouse: ON'
   #+end_src

# Toggle mouse off
   #+name: general-options
   #+begin_src shell-script
   bind M \
       set -g mode-mouse off \;\
       set -g mouse-resize-pane off \;\
       set -g mouse-select-pane off \;\
       set -g mouse-select-window off \;\
       display 'Mouse: OFF'
   #+end_src
* Colors
  extracted from
  https://github.com/seebi/tmux-colors-solarized/blob/master/tmuxcolors-256.conf

  Default statusbar colors
  #+name: general-options
  #+begin_src shell-script
  set-option -g status-bg colour235 #base02
  set-option -g status-fg colour136 #yellow
  set-option -g status-attr default
  #+end_src

  Default window title colors

  #+name: general-options
  #+begin_src shell-script
  set-window-option -g window-status-fg colour244 #base0
  set-window-option -g window-status-bg default
  #+end_src

  Active window title colors

  #+name: general-options
  #+begin_src shell-script
  set-window-option -g window-status-current-fg colour166 #orange
  set-window-option -g window-status-current-bg default
  #+end_src

  Pane border
  #+name: general-options
  #+begin_src shell-script
  set-option -g pane-border-fg colour235 #base02
  set-option -g pane-active-border-fg colour240 #base01
  #+end_src

  Message text
  #+name: general-options
  #+begin_src shell-script
  set-option -g message-bg colour235 #base02
  set-option -g message-fg colour166 #orange
  #+end_src
  
  Pane number display
  #+name: general-options
  #+begin_src shell-script
  set-option -g display-panes-active-colour colour33 #blue
  set-option -g display-panes-colour colour166 #orange
  #+end_src
  
  Clock
  #+name: general-options
  #+begin_src shell-script
  set-window-option -g clock-mode-colour green #green
  #+end_src

* Misc settings
  extracted from <https://github.com/tony/tmux-config>
  #+name: general-options
  #+begin_src shell-script
  set -g status-interval 1
  set -g status-justify centre # center align window list
  set -g status-left-length 20
  set -g status-right-length 140
  set -g status-left '#[fg=green]#H #[fg=black]• #[fg=green,bright]#(uname -r | cut -c 1-6)#[default]'
  set -g status-right '#[fg=green,bg=default,bright]#(tmux-mem-cpu-load 1) #[fg=red,dim,bg=default]#(uptime | cut -f 4-5 -d " " | cut -f 1 -d ",") #[fg=white,bg=default]%a%l:%M:%S %p#[default] #[fg=blue]%Y-%m-%d'
  #+end_src

  Solves slight delay when switching modes in vim
  #+name: general-options
  #+begin_src shell-script
  set -sg escape-time 0
  #+end_src

* Instructions for file tangling
  #+BEGIN_SRC shell-script :tangle tmux.conf.symlink :noweb no-export :exports code
    # Do not modify this file by hand.  It was automatically generated
    # from `tmux.org` in the same directory. See that file for more
    # information.

    <<startup>>
    <<general-options>>
  #+END_SRC
