#+TITLE: Making Emacs Work For Me
#+AUTHOR: Victor Santos (vct)
#+EMAIL: victor.phb@gmail.com

* Configuring Emacs using literate programming

  This is another attempt at creating a readable and maintainable Emacs
  configuration. I'm hopeful that using Org-Babel and a literate
  programming style will help tame the spaghettification.

* Start up

  Start with the scratch buffer; no start up screen.

  #+NAME: startup
  #+BEGIN_SRC emacs-lisp
  (setq inhibit-startup-message t)
  #+END_SRC
** CUA mode
  #+NAME: startup
  #+BEGIN_SRC emacs-lisp
  (cua-mode t)
  #+END_SRC
** Backup files
  #+name: startup
  #+begin_src emacs-lisp
  ;; store all backup and autosave files in the tmp dir
  (setq backup-directory-alist
        `((".*" . ,temporary-file-directory)))
  (setq auto-save-file-name-transforms
        `((".*" ,temporary-file-directory t)))
  #+end_src
* Package Management

  For installing packages using ELPA, MELPA, Marmalade.

  #+name: package-management
  #+begin_src emacs-lisp
  (when (>= emacs-major-version 24)
    (require 'package)
    (add-to-list 'package-archives '("marmalade" . "http://marmalade-repo.org/packages/"))
    (add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/"))
    (package-initialize)
  )
  #+end_src

* Path

  Add custom paths to emacs.

  #+name: package-management
  #+begin_src emacs-lisp
  (add-to-list 'load-path "~/.emacs.d/custom/") ; Load custom libraries
  (add-to-list 'custom-theme-load-path "~/.emacs.d/themes") ; extra theme path
  #+end_src

* Graphics and looks
** Color theme
   Leuven theme is awesome!

   #+name: look-and-feel
   #+BEGIN_SRC emacs-lisp
   (load-theme 'ujelly)
   #+END_SRC

** Font

   I like [[http://www.levien.com/type/myfonts/inconsolata.html][Inconsolata]], but it doesn't support a wide range of Unicode
   characters, so I fall back on [[http://dejavu-fonts.org/wiki/Main_Page][DejaVu Sans]] for those.

   #+name: look-and-feel
   #+BEGIN_SRC emacs-lisp
     (set-face-attribute 'default nil
                         :family "Inconsolata"
                         :height 130
                         :weight 'normal
                         :width 'normal)

    (set-face-attribute 'italic nil
                         :family "DejaVu Sans Mono"
                         :height 115
                         :weight 'normal
                         :width 'normal)

     (when (functionp 'set-fontset-font)
       (set-fontset-font "fontset-default"
                         'unicode
                         (font-spec :family "DejaVu Sans Mono"
                                    :width 'normal
                                    :size 12.4
                                    :weight 'normal)))

   #+END_SRC

** Reduce clutter

   Remove the toolbar. It's ugly and I never use it. Also remove the
   scroll bars and menu bar; below, I set up the fringe to show my position in a
   buffer.

   #+name: look-and-feel
   #+BEGIN_SRC emacs-lisp
   (tool-bar-mode -1)
   (toggle-scroll-bar -1)
   (menu-bar-mode -1)
   #+END_SRC

** Fringe decorations

   [[http://www.emacswiki.org/emacs/TheFringe][The fringe]] is the vertical region at the right and left of the
   buffer. Emacs lets you customize it of course.

   Here I set up buffer position in the fringe.

   #+NAME: look-and-feel
   #+BEGIN_SRC emacs-lisp
   (setq-default indicate-buffer-boundaries 'left)
   (setq-default indicate-empty-lines +1)
   #+END_SRC

** Mode line

   I'm using smart mode line to clean up the modeline display a little.

   #+NAME: look-and-feel
   #+BEGIN_SRC emacs-lisp
   ;; These two lines are just examples
   (setq powerline-arrow-shape 'curve)
   (setq powerline-default-separator-dir '(right . left))
   ;; These two lines you really need.
   (setq sml/theme 'powerline)
   (sml/setup)
   ;;(sml/setup)
   ;;(sml/apply-theme 'dark)
   ;;(setq sml/shorten-directory t)
   ;;(setq sml/shorten-modes t)
   #+END_SRC

* Org Mode
** Org-Babel
*** Fontifying source blocks

    Enable syntax highlighting in src blocks.

    #+name: org-config
    #+BEGIN_SRC emacs-lisp
      (setq-default org-src-fontify-natively t)
    #+END_SRC

* Configuration file layout

  Here I define the emacs.el file that gets generated by the code in
  this org file.

  #+BEGIN_SRC emacs-lisp :tangle emacs.symlink :noweb no-export :exports code
    ;;;; Do not modify this file by hand.  It was automatically generated
    ;;;; from `emacs.org` in the same directory. See that file for more
    ;;;; information.

    <<startup>>
    <<general>>
    <<package-management>>
    <<environment>>
    <<tools>>
    <<customize-config>>
    <<look-and-feel>>
    <<formatting>>
    <<programming-setup>>
    <<auto-complete>>
    <<global-keys>>
    <<global-navigation>>
    <<org-config>>
    <<libraries>>
  #+END_SRC
