#!/bin/bash
# Compare two files and check if they are duplicates

fname1=$1
fname2=$2

cmp -s ${fname1} ${fname2} > /dev/null
if [ $? -eq 1 ]; then
    echo "The files are different"
else
    echo "The files are duplicates"
fi

